configfile: 'config.yaml'

rule all:
    input:
        config['qc_config_out']

rule fastqc_config:
    params:
        fastqs=config['qc_config_in'],
        outdir=config['qc_config_out']
    output:
        config['qc_config_out']
    script:
        "fastqc_config.py"
