data_dir: data/fastq
output_dir: output/
log_dir: logs/
sample_regex: '_[0-9]*.$'
end_denote:
  R1: forward
  R2: backward
fastp_params: '--low_complexity_filter --low_complexity_threshold 30'
treatment_regex: ['^ASW', '^Chlorate', '^DMSO', '^MK886']
bad_threshold: 50000
ugly_threshold: 250000