dirs:
  data: /home/dakota/PythonModules/scPipe/data/fastq
  output: /home/dakota/PythonModules/scPipe/output/
  log: /home/dakota/PythonModules/scPipe/logs/
  genome: /home/dakota/SequenceData/GenomeAnnotations/star/
  matrices: ['/home/dakota/PythonModules/scPipe/output/tmp']
files:
  gtf: /home/dakota/SequenceData/GenomeAnnotations/lv_genome_annotations.gtf
  genome_fasta: '/home/dakota/SequenceData/Genomes/Lytechinus_variegatus_genome.fa'
end_denote:
  R1: forward
  R2: backward
thresholds:
  bad: 50000
  ugly: 250000
params:
  fastp: '-y -Y 30'
  star_genome: ''
  star_align: '--runThreadN 2'
  featureCount: ''
sample_regex:
  id: '_[0-9]*.$'
  batch: 
    1: '-1-'
    2: '-2-'
    3: '-3-'
  treatment: 
    ASW: '^ASW'
    Chlorate: '^Chlorate'
    DMSO: '^DMSO'
    MK886: '^MK886'
flags:
  star_est_ChrBinsNbits: True
  combine_count_matrices: True
read_length: 152

